language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.11-dev"
  - "nightly"  # nightly build

install:
  - pip install zc.buildout==2.13.3
  - pip install virtualenv
  - buildout

script:
  - bin/pytest
